### PR TITLE
readme: how to use guide added

### PR DESCRIPTION
**Pull request by omurbekjk**
how to use guide added

### CODE REVIEW

**Comment by alexbezhan** [comment]
Thanks @omurbekjk for the contribution! 🚀

**Comment by omurbekjk** [comment]
I watched your tutorials, what about adding screen for followers and following users?

**Comment by alexbezhan** [comment]
There are additional tutorials on my website. You may take a look at those. They are for paid users, though.

**Comment by omurbekjk** [comment]
Yeap, I take a look to them. They were about making scalable apps, maybe i missed followers/followings part.

**Comment by omurbekjk** [comment]
do you have plans to improve this project or improved version will be available only for paid users?

**Pull request merged**
